#!/usr/bin/env python3

import requests
try:
    r = requests.get('https://api.coindesk.com/v1/bpi/currentprice/USD.json');
    ticker = r.json()

    print('%.2f$' % float(ticker['bpi']['USD']['rate'].replace(",","")))
except:
    print("Unknown")
